/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airlineproject;

/**
 *
 * @author USER
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addCustomerMenu = new javax.swing.JMenuItem();
        searchCustomerMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addFlightMenu = new javax.swing.JMenuItem();
        bookTicketMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ticketMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        addAdminMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        jMenu1.setText("Customer");

        addCustomerMenu.setText("Add Customer");
        addCustomerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerMenuActionPerformed(evt);
            }
        });
        jMenu1.add(addCustomerMenu);

        searchCustomerMenu.setText("Search Customer");
        searchCustomerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerMenuActionPerformed(evt);
            }
        });
        jMenu1.add(searchCustomerMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Flight");

        addFlightMenu.setText("Add Flight");
        addFlightMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightMenuActionPerformed(evt);
            }
        });
        jMenu2.add(addFlightMenu);

        bookTicketMenu.setText("Book Flight");
        bookTicketMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketMenuActionPerformed(evt);
            }
        });
        jMenu2.add(bookTicketMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Generate Ticket");

        ticketMenu.setText("Ticket");
        ticketMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketMenuActionPerformed(evt);
            }
        });
        jMenu3.add(ticketMenu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Admin");

        addAdminMenu.setText("Add Admin");
        addAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminMenuActionPerformed(evt);
            }
        });
        jMenu4.add(addAdminMenu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMenuActionPerformed
        // TODO add your handling code here:
        AddCustomer customer=new AddCustomer();
        Desktop.add(customer);
        customer.setVisible(true);
    }//GEN-LAST:event_addCustomerMenuActionPerformed

    private void addFlightMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightMenuActionPerformed
        // TODO add your handling code here:
        AddFlight flight=new AddFlight();
        Desktop.add(flight);
        flight.setVisible(true);
    }//GEN-LAST:event_addFlightMenuActionPerformed

    private void addAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminMenuActionPerformed
        // TODO add your handling code here:
        AddAdmin admin=new AddAdmin();
        Desktop.add(admin);
        admin.setVisible(true);
    }//GEN-LAST:event_addAdminMenuActionPerformed

    private void searchCustomerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerMenuActionPerformed
        // TODO add your handling code here:
        SearchCustomer search=new SearchCustomer();
        Desktop.add(search);
        search.setVisible(true);
    }//GEN-LAST:event_searchCustomerMenuActionPerformed

    private void bookTicketMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketMenuActionPerformed
        // TODO add your handling code here:
        BookTicket ticket=new BookTicket();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_bookTicketMenuActionPerformed

    private void ticketMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketMenuActionPerformed
        // TODO add your handling code here:
        GetTicket ticket=new GetTicket();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_ticketMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem addAdminMenu;
    private javax.swing.JMenuItem addCustomerMenu;
    private javax.swing.JMenuItem addFlightMenu;
    private javax.swing.JMenuItem bookTicketMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem searchCustomerMenu;
    private javax.swing.JMenuItem ticketMenu;
    // End of variables declaration//GEN-END:variables
}
